[tool.poetry]
name = "fake-service"
version = "0.1.0"
description = ""
authors = ["Jefferson Fragoso de Souza <jefferson.fragoso.ext@jeitto.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
